---

- project:
    templates:
      - check-requirements
      - openstack-python3-jobs
      - openstack-python3-jobs-arm64
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-pylint
        - freezer-tempest-basic
    gate:
      jobs:
        - openstack-tox-pylint
        - freezer-tempest-basic
