- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - freezer-api-ubuntu
        - freezer-api-centos-7:
            voting: false
        - openstack-tox-pylint
        - freezer-tempest-basic
        - freezer-tempest-basic-sqlalchemy
    gate:
      jobs:
        - freezer-api-ubuntu
        - openstack-tox-pylint
        - freezer-tempest-basic
        - freezer-tempest-basic-sqlalchemy
    experimental:
      jobs:
        - freezer-api-opensuse-423

- job:
    name: freezer-api-ubuntu
    parent: legacy-dsvm-base
    run: playbooks/legacy/freezer-api-ubuntu/run.yaml
    post-run: playbooks/legacy/freezer-api-ubuntu/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-web-ui
      - openstack/python-freezerclient
      - openstack/freezer-tempest-plugin

- job:
    name: freezer-api-centos-7
    parent: legacy-dsvm-base
    run: playbooks/legacy/freezer-api-centos-7/run.yaml
    post-run: playbooks/legacy/freezer-api-centos-7/post.yaml
    timeout: 7800
    nodeset: legacy-centos-7
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-web-ui
      - openstack/python-freezerclient
      - openstack/freezer-tempest-plugin

- job:
    name: freezer-api-opensuse-423
    parent: legacy-dsvm-base
    run: playbooks/legacy/freezer-api-opensuse-423/run.yaml
    post-run: playbooks/legacy/freezer-api-opensuse-423/post.yaml
    timeout: 7800
    nodeset: legacy-opensuse-423
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-web-ui
      - openstack/python-freezerclient
      - openstack/freezer-tempest-plugin


- job:
    name: freezer-tempest-basic-sqlalchemy
    parent: devstack-tempest
    timeout: 7200
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/python-openstackclient
      - openstack/python-freezerclient
      - openstack/freezer
      - openstack/freezer-api
      - openstack/freezer-tempest-plugin
      - openstack/tempest
    vars:
      devstack_plugins:
        freezer-api: https://git.openstack.org/openstack/freezer-api
      devstack_services:
        tls-proxy: false
        freezer-api: true
        tempest: true
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
      devstack_localrc:
        FREEZER_BACKEND: 'sqlalchemy'
        TEMPEST_PLUGINS: '/opt/stack/freezer-tempest-plugin'
      tempest_test_regex: '^(freezer_tempest_plugin.tests.freezer_api)'
      tox_envlist: all
      tox_environment:
        PYTHONUNBUFFERED: 'true'
      zuul_copy_output:
        /etc/hosts: logs
